"""Investigation data models."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any


@dataclass
class TimelineEntry:
    """Single timeline item discovered during tracing."""

    url: str
    title: str
    date: str | None


@dataclass
class DomainIntelResult:
    """Domain intelligence outcomes."""

    domain: str
    age_days: int | None
    registrar: str | None
    dns_records: dict[str, list[str]]
    crt_issued: list[str]
    archive_snapshots_found: bool


@dataclass
class MediaForensicsResult:
    """Image metadata and hashing findings."""

    file_path: str
    exif: dict[str, Any]
    perceptual_hash: str | None
    duplicate_warning: bool


@dataclass
class NetworkAnalysisResult:
    """Propagation graph summary."""

    earliest_poster: str | None
    node_count: int
    edge_count: int
    top_degree_nodes: list[tuple[str, float]]


@dataclass
class ClaimAnalysisResult:
    """NLP-derived claim assessment."""

    entities: list[str]
    emotional_language_score: float
    factual_components: list[str]


@dataclass
class InvestigationReport:
    """Full report generated by `investigate` workflow."""

    claim_input: str
    input_type: str
    claim_analysis: ClaimAnalysisResult
    timeline: list[TimelineEntry] = field(default_factory=list)
    earliest_source: TimelineEntry | None = None
    domain_intel: DomainIntelResult | None = None
    media_forensics: MediaForensicsResult | None = None
    network_analysis: NetworkAnalysisResult | None = None
    credibility_score: float = 0.0
    confidence_level: str = "LOW"
    score_explanation: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert report to serializable dictionary."""
        return asdict(self)
